### ISSUE TITLE
F03 - Logging to .log files

### ISSUE THREAD

**Issue by krzysztofreczek** [krzysztofreczek/how-long#10]
Problem:
Currently there is not logging within the application. All usages and potentials issues should be logged into the .log file.

AC:
- All logs are logged in configurable .log file. Default location: ~/.how-long/<app-name>.log

**Comment by krzysztofreczek** [comment]
Created a followup issue to resolve some of the issues reported in the PR. https://github.com/krzysztofreczek/how-long/issues/29

**Comment by 1milosz2** [comment]
Done.
