### ISSUE TITLE
F09 - Parametrized testing

### ISSUE THREAD

**Issue by krzysztofreczek** [krzysztofreczek/how-long#18]
Lots of unit tests in our code are similar with just few argument/expected value differences. It is a typical case for parametrized unit testing.

https://blog.codefx.org/libraries/junit-5-parameterized-tests/

AC:
Refactoring candidate tests are recognized and parametrized.

**Comment by 1milosz2** [comment]
Sure, I'll take care of this.

**Comment by 1milosz2** [comment]
Done.
