### ISSUE TITLE
F02 - Finalize Admin implementation

### ISSUE THREAD

**Issue by krzysztofreczek** [krzysztofreczek/how-long#5]
Admin application has to be finalized. The following functionalities/command should be handled:
- LIST <o:MONTH> - will list all records for given month / when month not provided use current month instead
- UPDATE <r:MONTH> <r:DAY> <r:UPDATE_MODE> <r:START_TIME> <o:END_TIME>
*UPDATE_MODE: {FULL, START, END}
*TIME format: hh:mm:ss
*example: UPDATE 8 12 FULL 08:15:00 16:31:30
*example: UPDATE 8 12 START 08:15:00
*example: UPDATE 8 12 END 16:31:30
- DELETE <r:MONTH> <r:DAY>

r - required, o - optional
In case of improper usage display usage hints.

Hints:
- Please follow CommandResolver pattern: There is one common Command interface with multiple implementations. CommandResolves resolves adequate command in accordance with given app arguments. Resolved command is executed. Please look into Printer resolution implementation within how-long-app.

Acceptance criteria:
- All three commands are implemented
- All commands are covered with unit tests
- Exception handling/misusage is covered

**Comment by 1milosz2** [comment]
Hi Krzysztof,

I know it's been a while since you posted the issue above, but I'm slowly proceeding with the Admin implementation. Currently I believe I succeeded in meeting first of the acceptance criteria. Although I’m not sure whether method printUsage () in ArgumentResolver class is necessary? Would you be that kind and let me know if I’m supposed to add methods body or if I can just delete it? For now I just commented it out.

**Comment by krzysztofreczek** [comment]
Hi, As far I remember this method has been left as a placeholder for implementation of "In case of improper usage display usage hints." requirement. I foreseen this method to be called in case an improper usage of commands is recognised. Of course it is up to you how you implement that feature. Do not hesitate to remove code you do not use. YAGNI:)

**Comment by krzysztofreczek** [comment]
I have created a fork repo with admin architecture recommendation: https://github.com/nhood-org/how-long. Feel free to visit and adopt into your branch.
