### ISSUE TITLE
F03 - Add readme files to project modules

### ISSUE THREAD

**Issue by krzysztofreczek** [krzysztofreczek/how-long#6]
Add readme files with the following content:
- General application/module description
- Build, Installation and Run procedures

**Comment by krzysztofreczek** [comment]
Implemented without pull request

**Comment by krzysztofreczek** [comment]
@1milosz2, I have added README.md files to all modules. Have a look if possible. Make sure you have your branch rebased in case on any pull request mergeability issues.

**Comment by 1milosz2** [comment]
Thanks for the info. I merged your changes into my branch.
